### ISSUE TITLE
"Handling file uploads" example wrong key

### ISSUE THREAD

**Issue by Tsuribori** [kit-clj/kit-clj.github.io#29]
Regarding the "Handling file uploads" code example

https://github.com/kit-clj/kit-clj.github.io/blob/3ee6e6952c67c7cd4fa7f25d357d2f182873b4d3/resources/md/routes.md?plain=1#L147-L157

With 
```clojure
ring/ring-core {:mvn/version "1.9.5"}
ring/ring-defaults {:mvn/version "0.3.3"}
```

there is no `:parameters` key but rather the following
```
(:reitit.core/match :reitit.core/router :protocol :cookies :remote-addr :params :flash :headers :server-port :content-length :form-params :websocket? :session/key :server-exchange :query-params :content-type :character-encoding :context :uri :server-name :anti-forgery-token :query-string :path-params :body :multipart-params :scheme :request-method :session)
```

The `:multipart-params` contains the parameters in string-key form while the same things are in `:params` in keyword-key form. This seems to be because `ring-defaults` [doesn't do anything to `:multipart-params`](https://github.com/ring-clojure/ring-defaults/blob/master/src/ring/middleware/defaults.clj).

Should the example be fixed to using `:params`?

**Comment by yogthos** [comment]
Good catch, Reitit uses `:parameters`, but Ring middleware for multipart params uses a `:params` key.
