### ISSUE TITLE
Guestbook example `:main-opts` for alias `:dev` is tripping up Calva

### ISSUE THREAD

**Issue by PEZ** [kit-clj/kit-clj.github.io#32]
Hello, thanks for providing this framework and all the documentation!

Is there a reason that the `:dev` alias has an empty `:main-opts` vector in the Guestbook example? It trips Calva up. I should probably fix this in Calva, but also wondering if there isn't a reason, then I can PR a `:dev` alias that doesn't have `:main-opts` specified. And maybe add a note or two about Calva in the docs.

**Comment by yogthos** [comment]
It's mostly there as a placeholder, so definitely ok to remove it in my opinion. It probably would be good for Calva to handle it though as it's not technically incorrect to have empty `main-opts`.

**Comment by PEZ** [comment]
Agree that Calva should handle it.
