### ISSUE TITLE
Unclear how to use transactions

### ISSUE THREAD

**Issue by vemv** [kit-clj/kit-clj.github.io#42]
Hi!

Even after reading the docs and misc related source code I don't have it clear how to use transactions. I am able to grab a `:db.sql/query-fn` and a `:db.sql/connection` from my Integrant system, but I'm not sure of those would compose to something that looked like:

```clj
(with-transaction conn
  (query-fn conn :foo ,,,)
  (query-fn conn :bar ,,,))
```

(Well I did write something that appeared to make sense... but it may as well be considered a hack)

I'd appreciate a simple example with the specific namespaces/functions to be `require`d.

Cheers - V

**Comment by yogthos** [comment]
Adding an example for transactions is a good idea. In general, transactions work the same way as documented in [next.jdbc](https://github.com/seancorfield/next-jdbc/blob/develop/doc/transactions.md). For example, 

```clojure
(jdbc/with-transaction [tx conn]
  (query-fn tx :foo ...)
  (query-fn tx :bar ...))
```

The `conn` would come from your integrant component, and the would be assigned to `tx` within the scope of the transaction. Then you'd pass `tx` to the query functions.

**Comment by yogthos** [comment]
And I've updated the docs [here](https://kit-clj.github.io/docs/database.html#sql_queries). Let me know if that looks good.
