### ISSUE TITLE
Websockets server documentation

### ISSUE THREAD

**Issue by vemv** [kit-clj/kit-clj.github.io#43]
Hey there!

There doesn't appear to be documentation as for how to serve websockets requests.

It seems easy enough to link to https://github.com/luminus-framework/ring-undertow-adapter/tree/3b27314d3eb040c17a0e8dae081adead4feb844f#websocket-handler which might be all I needed.

Cheers - V

**Comment by yogthos** [comment]
Oh yeah good catch, let me add that in.

**Comment by yogthos** [comment]
and have the doc here https://kit-clj.github.io/docs/websockets.html
