### ISSUE TITLE
Unfinished sentence in middleware docs

### ISSUE THREAD

**Issue by gerdint** [kit-clj/kit-clj.github.io#44]
See end of this line:

https://github.com/kit-clj/kit-clj.github.io/blob/9218c235573b876d2c5b02ced9caaef0f744e418/resources/md/middleware.md?plain=1#L7

Not trying to nit-pick, just curious of what it was supposed to say!

**Comment by yogthos** [comment]
Actually, can't think of what I meant to say there. I just deleted the dangling sentence for now. I'll add something back in if it comes back to me. :)
