### ISSUE TITLE
Out of date or erroneous information in routing docs?

### ISSUE THREAD

**Issue by gerdint** [kit-clj/kit-clj.github.io#45]
Is the below information still accurate? I do not think there is an `app` route group out of the box. Or should it say `api`?

https://github.com/kit-clj/kit-clj.github.io/blob/9218c235573b876d2c5b02ced9caaef0f744e418/resources/md/routes.md?plain=1#L187

**Comment by yogthos** [comment]
Thanks for the heads up, looks like that got overlooked porting the docs from Luminus. I've updated to match the docs with the way things are set up in Kit.
