### ISSUE TITLE
Please add

### ISSUE THREAD

**Issue by mictadlo** [kit-clj/kit-clj.github.io#47]
Please add that `guestbook.clj` has to be created in `src/clj/kit/guestbook/web/controllers`

https://github.com/kit-clj/kit-clj.github.io/blob/30714b7896479570f0126f7ed932c3182081244b/docs/docs/guestbook.html#L62C1049-L62C1049

**Comment by yogthos** [comment]
I've updated the section on creating the controller to mention the file for the controller https://github.com/kit-clj/kit-clj.github.io/blob/master/resources/md/guestbook.md#creating-a-controller-for-the-guestbook
